[package]
name = "abigen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "1.0.0", features = ["legacy"] }
eyre = "0.6"
serde_json = "1.0.88"
ethers-solc = "1.0.2"
